### ISSUE TITLE
ical/.ics issue

### ISSUE THREAD

**Issue by tjcflys** [jshor/angular-addtocalendar#16] opened 2016-07-11 23:29 UTC
Have not been able to get iCalendar option to work with recent releases of iOS. I verified that your formatting is correct using the validator at icalendar.org. Could it be an issue with downloadjs? Any help would be greatly appreciated.

**Comment by jshor** [comment] 2016-07-11 23:39
It's indeed an issue with downloadjs. Unfortunately downloadjs doesn't work with Safari. I have plans to fix this soon with FileSaver however (see: http://stackoverflow.com/questions/12802109/download-blobs-locally-using-safari)

**Comment by tjcflys** [comment] 2016-07-12 05:34
I think that question might have been referring to Safari for OS. I tried filesaver and it does not seem to work. Filesaver's own documentation informs that it will not work with iOS. I decided to create the file server side and then serve it. Thanks for the help and good luck!

**Comment by jshor** [comment] 2016-07-18 16:27
@tjcflys you're right, there are issues with iOS using FileSaver.js:

> saveAs must be run within a user interaction event such as onTouchDown or onClick; setTimeout will prevent saveAs from triggering.

However I don't think this will be a problem with the `dlIcal()` function so I used [angular-file-saver](https://github.com/alferov/angular-file-saver) (a wrapper for FileSaver.js). It works on Safari desktop at least.

If you have a chance, could you please clone this repo and checkout to develop to see if the issue is fixed on iOS/safari?

**Comment by jshor** [comment] 2016-07-20 16:47
This appears to work in iOS versions I've tested - the latest fix is in v1.2.0

**Comment by tjcflys** [comment] 2016-07-21 06:53
Sorry it took so long to get back to you man. I just tried 1.2.0 on 2 different Apple devices with no luck. Screenshot is attached if that helps. 
![image](https://cloud.githubusercontent.com/assets/13263742/17013707/0aa2089e-4ed5-11e6-9547-275b3563ed24.png)

**Comment by jshor** [comment] 2016-07-21 14:08
Hey @tjcflys no worries - sorry to hear that the fix didn't work. I'm going to re-open this issue.

**Comment by fierysolid** [comment] 2016-08-11 03:32
Any news on this? I've been googling like mad to find a solution.

**Comment by jshor** [comment] 2016-08-11 14:41
@fierysolid unfortunately no, sorry. According to [this](https://github.com/eligrey/FileSaver.js/issues/129) it looks like iOS Safari will always render the file name as "Unknown."

I might end up implementing browser detection for Safari and having the menu not show options for icalendar on iOS safari. It's a shitty solution for sure.

**Closed** 2017-09-01 16:42 UTC
Labels: bug, help wanted

**Comment by jhallmusic** [comment] 2017-11-11 23:31
Hi @jshor I noticed you closed this a couple months ago, is there still no solution? I'm still experiencing this, and it seems that maybe there's a fix from the link you provided above. thanks!
